### ISSUE TITLE
Followed installation to the letter but @parcel/core: Failed to resolve 'src/index.html' 

### ISSUE THREAD

**Issue by laurencefass** [CaioOliveira793/parcel-resolver-typescript-module#1]
Ive installed this in my parcel project and im getting an error when i npm run dev.

```
@parcel/core: Failed to resolve 'src/index.html' 
parcel-resolver-typescript-module: Ts config error invalid_json

  Error: Ts config error invalid_json
      at $9eb26000948b9f3f$var$loadAndParse (/Users/laurence.fass/SSG/events-service-ui/node_modules/parcel-resolver-typescript-module/dist/main.js:212:15)
      at async $9eb26000948b9f3f$export$a2471833b3813ee7 
  (/Users/laurence.fass/SSG/events-service-ui/node_modules/parcel-resolver-typescript-module/dist/main.js:195:20)
      at async Object.resolve (/Users/laurence.fass/SSG/events-service-ui/node_modules/parcel-resolver-typescript-module/dist/main.js:244:55)
      at async ResolverRunner.resolve (/Users/laurence.fass/SSG/events-service-ui/node_modules/@parcel/core/lib/requests/PathRequest.js:214:22)
      at async Object.run (/Users/laurence.fass/SSG/events-service-ui/node_modules/@parcel/core/lib/requests/PathRequest.js:104:16)
      at async RequestTracker.runRequest (/Users/laurence.fass/SSG/events-service-ui/node_modules/@parcel/core/lib/RequestTracker.js:756:20)
      at async AssetGraphBuilder.runPathRequest 
  (/Users/laurence.fass/SSG/events-service-ui/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:844:18)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn 
  (/Users/laurence.fass/SSG/events-service-ui/node_modules/@parcel/utils/lib/index.js:33579:13)
      at async $b0fd219fea43bcac$export$2e2bcd8739ae039._next (/Users/laurence.fass/SSG/events-service-ui/node_modules/@parcel/utils/lib/index.js:33572:9)
```

my parcelrc file is exactly this:

```
{
	"extends": "@parcel/config-default",
	"resolvers": [
		"parcel-resolver-typescript-module",
		"..."
	],
	"transformers": {
		"*.{ts,tsx}": [
			"@parcel/transformer-typescript-tsc"
		]
	}
}
```

my tsconfig  "compilerOptions"
 
```
        "baseUrl": ".",
        "paths": {
            "@src/*": ["src/*"],
            "@components/*": ["src/customComponents/*"],
            "@types": ["src/types/index.ts"],
            "@resources": ["src/resources/index.ts"],
            "@consts/*": ["src/consts/*"],
            "@utils/*": ["src/utils/*"]
        }
```

package.json 

```
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "npx jest",
    "test:watch": "npx jest --watch",
    "lint": "npx eslint . --ext .ts --ext .tsx",
    "lint:fix": "npx eslint . --fix --ext .ts --ext .tsx",
    "dev": "npx parcel src/index.html -p 1234",
    "start": "http-server ./dist-${NODE_ENV} -p 1234 --proxy http://localhost:1234/? ./dist-${NODE_ENV}",
    "check": "npx tsc",
    "build": "npm run lint && npm run check && parcel build src/index.html",
    "api": "node api/api.js",
    "prettier:check": "prettier --check .",
    "prettier:format": "prettier --write ."
  },
  "repository": {
    "type": "git",
    "url": "ssh://git@bitbucket.spotlightsportsgroup.com/b2b/events-service-ui.git"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@ssgat/api-ui-core": "^0.0.40",
    "@tinymce/tinymce-react": "^4.2.0",
    "http-server": "^14.1.0",
    "lodash": "^4.17.21",
    "oddslib": "^2.1.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-router-dom": "^6.3.0",
    "swr": "^1.3.0"
  },
  "devDependencies": {
    "@parcel/plugin": "^2.8.2",
    "@parcel/transformer-sass": "^2.7.0",
    "@types/jest": "^29.2.5",
    "@types/node": "^18.11.18",
    "@types/react-dom": "^18.0.10",
    "@typescript-eslint/eslint-plugin": "^5.48.0",
    "@typescript-eslint/parser": "^5.48.0",
    "buffer": "^6.0.3",
    "crypto-browserify": "^3.12.0",
    "eslint": "^8.31.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-unused-imports": "^2.0.0",
    "events": "^3.3.0",
    "jest": "^29.3.1",
    "parcel": "^2.7.0",
    "parcel-resolver-typescript-module": "^0.1.8",
    "path-browserify": "^1.0.1",
    "prettier": "2.7.1",
    "process": "^0.11.10",
    "stream-browserify": "^3.0.0",
    "ts-jest": "^29.0.3",
    "typescript": "^4.9.4"
  },
  "os": [
    "darwin",
    "linux"
  ],
  "cpu": [
    "x64",
    "arm64"
  ]
}

```

**Comment by CaioOliveira793** [comment]
The error `Ts config error invalid_json` is thrown when a `tsconfig.json` file content is not valid **JSON**.

Note that some differences exists between `JSONC` (JSON with comments), `JSON5` (JSON with extensions) and `JSON`, which is the format expected by this library.

As a smaller step to resolve this issue, I recommend removing comments and trailing commas from the `tsconfig.json` files. If somehow the error persists, please add a minimal reproduction repository.
